#8111
#Thu Jan 29 23:07:15 CST 2026
disableEngineInfoThrust=false
disableEngineInfoThrottle=true
disableFlightInfoCompass=false
enableStatusBar=false
disableFlightInfoAcc=false
enableAxisEdge=false
disableFlightInfoRadioAlt=false
disableFlightInfoTAS=false
voiceVolume=80
engineInfoEdge=false
disableHUDAoA=false
usetexturecrosshair=true
engineInfoColumn=1
disableEngineInfoTemp=false
disableHUDSEPLabel=true
disableFlightInfoWingSweep=false
disableEngineInfoHorsePower=false
disableEngineInfoFuelTime=false
disableEngineInfoPitch=true
attitudeIndicatorUseNumColor=false
miniHUDaoaBarWarningRatio=0.25
flightInfoFontadd=0
displayCrosshair=false
MonoNumFont=Sarasa Mono SC
enablegearAndFlaps=false
drawHUDtext=true
disableFlightInfoAoS=false
AAEnable=true
hudMach=true
disableFlightInfoMach=false
drawHUDAttitude=true
flightInfoFontC=Sarasa Mono SC
flightInfoColumn=1
flightInfoFontaddC=0
crosshairScale=115
disableEngineInfoRadiator=true
disableEngineInfoEffEta=false
disableFlightInfoAoA=false
fontNumR=255
disableFlightInfoTurn=false
disableEngineInfoMixture=true
fontWarnR=255
enableLogging=false
disableFlightInfoTurnRadius=false
crosshairSwitch=true
scrosshairName=ez42_collimator
fontUnitR=210
fontNumG=255
fontNumB=255
fontWarnG=0
fontNumA=255
disableEngineInfoCompressor=false
disableFlightInfoIAS=false
fontWarnB=0
fontUnitG=85
fontWarnA=255
attitudeIndicatorHeight=174
GlobalNumFont=Sarasa Mono SC
disableFlightInfoNy=false
fontUnitB=61
Interval=50
fontUnitA=255
engineControlY=880
engineControlX=128
disableFlightInfoSEP=false
attitudeIndicatorY=239
attitudeIndicatorX=1683
flapsControlSwitch=false
stickValueY=503
enableAttitudeIndicator=false
stickValueX=2314
disableHUDHeightLabel=true
engineInfoFontadd=0
engineInfoFont=Sarasa Mono SC
fontShadeR=0
disableEngineInfoHeatTolerance=false
disableFlightInfoVario=false
attitudeIndicatorWidth=233
selectedFM1=bf-109g-6
flightInfoEdge=false
selectedFM0=bf-109g-10
simpleFont=true
disableHUDSpeedLabel=true
crosshairName=0\u7A7A\u767D
disableEngineInfoLFuel=true
fontShadeG=0
enableFlapAngleBar=false
attitudeIndicatorFreqMs=110
disableEngineInfoOilTemp=false
fontLabelR=255
disableEngineInfoPropPitch=false
fontShadeB=0
disableEngineInfoPressure=false
crosshairY=991
fontShadeA=255
flightInfoY=109
crosshairX=1050
flightInfoX=262
enableVoiceWarn=true
enableFMPrint=false
usetempInfoSwitch=true
fontLabelG=255
engineInfoSwitch=true
fontLabelB=255
fontLabelA=255
enableEngineControl=false
enableAltInformation=true
disableEngineInfoWepKg=false
gearAndFlapsY=473
gearAndFlapsX=355
disableEngineInfoWepTime=false
disableFlightInfoHeight=false
flightInfoSwitch=false
enablegearAndFlapsEdge=false
enableAxis=false
disableEngineInfoRPM=false
disableEngineInfoEffHp=false
engineInfoY=662
engineInfoX=241
disableEngineInfoPowerPercent=false
displayFmKey=25
miniHUDaoaWarningRatio=0.2
situationAwareY=-13
situationAwareX=2329
disableFlightInfoWx=false
disableEngineInfoFuelKg=false
disableEngineInfoEngResponse=false
